### ISSUE TITLE
Page not found (404) error while redirecting to payment screen

### ISSUE THREAD

**Issue by Jitheesh** [Ingenico-ePayments/connect-extension-magento2#7] opened 2020-02-18 07:24 UTC
For some orders we are facing 404 error after clicking place order button. Customer is redirected to 
https://payment.pay1.preprod.secured-by-ingenico.com/checkout/xxxx-8d4624e4fc6344c9986b8d4d2dffc27c:f062a20f-43d8-4505-9c24-b548b1fe5d40:d8d08c6db3294ed1837fa5bd6032b36b

xxxx => Merchant Id

**Comment by kanduvisla** [comment] 2020-02-18 09:14
Hi @Jitheesh ,

You mention "some orders", so I'm assuming that not all orders have this issue. Could you please check what these orders have in common? The `additional_information`-column in the `sales_order_payment` might give a bit more information.

Also: could you share some details? Are you using Hosted Checkout for example? Or share a log record of a specific case so we can try to reproduce it?

**Comment by Jitheesh** [comment] 2020-02-18 09:25
Hi @kanduvisla 

We are using hosted checkout. We don't have more details about this issue but it happens occasionally and if it happens all other next checkouts from same session will end with 404 page.

This issue cleared if user clear cookies and try again.

**Comment by kanduvisla** [comment] 2020-02-18 09:29
Hi @Jitheesh , is the URL the customer is redirected to the same as the `partialRedirectUrl` in the response body in the logs (when requesting a hosted checkout)? Please note, in the response body this is minus the `https://payment.`-prefix.

Also: if you go to this URL directly (copy/paste it from the log), does it then also trigger a 404?

**Comment by kanduvisla** [comment] 2020-02-18 09:30
One last question: are you using different merchant ID's?

**Comment by kanduvisla** [comment] 2020-02-18 09:46
Hi @Jitheesh ,

In issue #5 you mention that you're using a OneStep checkout module. Could you please check if the problem described in this issue is reproducible using the default Magento Checkout?

**Comment by jitheesh-db** [comment] 2020-02-18 11:30
> One last question: are you using different merchant ID's?

No we are using same merchant Id

**Comment by Ingenico-Shoppingcarts-zz** [comment] 2020-02-19 09:12
Hi @jitheesh-lumi, I'm only known with the 404 in combination with the Hosted Checkout when an old session is loaded. A RPP sessions is valid for 2 hours. 
To my knowledge we do not store any sessions in cookies. So I'm curious to the relationship of the consumer Cookies. I'll look in to the issue if we can find any relation to the 404

```
{
   "errorId": "5e4cf727ea49fa707de5c5d130f518d0",
   "errors": [
      {
         "code": "1010",
         "id": "UNKNOWN_HOSTED_CHECKOUT_ID",
         "category": "CONNECT_PLATFORM_ERROR",
         "propertyName": "hostedCheckoutId",
         "message": "UNKNOWN_HOSTED_CHECKOUT_ID",
         "httpStatusCode": 404
      }
   ]
}
```

**Comment by Jitheesh** [comment] 2020-02-24 12:20
Hi @Ingenico-Shoppingcarts 

Do you have any further updates on this, I'm still getting 404 response https://payment.pay1.preprod.secured-by-ingenico.com/checkout/xxx-d97bd29a12644a09a35dc73a09ca1571:b40ffd58-18ad-4fd6-bc2b-1fdab76bf884:cbb614fee3564a4a82c19d4bde64288d

**Comment by kanduvisla** [comment] 2020-02-24 12:29
Hi @Jitheesh ,

Could you answer the following questions:

- Is the URL the customer is redirected to the same as the partialRedirectUrl in the response body in the logs (when requesting a hosted checkout)? Please note, in the response body this is minus the https://payment.-prefix.
- If you go to this URL directly (copy/paste it from the log), does it then also trigger a 404?
- Is this behavior reproducible using the default Magento checkout (not with a third party checkout module)?

**Comment by Jitheesh** [comment] 2020-02-24 12:43
- Is the URL the customer is redirected to the same as the partialRedirectUrl in the response body in the logs : yes
`[2020-02-24 09:31:49] report.INFO: Incoming response from https://world.preprod.api-ingenico.com (requestId='1908d028-296e-40ac-a40f-38d30d993bc3')
HTTP/1.1 201
Date: Mon, 24 Feb 2020 09:31:49 GMT
Server: Apache
X-OneAgent-JS-Injection: true
Location: https://world.preprod.api-ingenico.com/v1/xxxx/hostedcheckouts/b40ffd58-18ad-4fd6-bc2b-1fdab76bf884
Content-Type: application/json
Set-Cookie: dtCookie=54$E5F0EF6D0CF0A148E98D40A1BE504263; Path=/; Domain=.api-ingenico.com
Transfer-Encoding: chunked

{
    "RETURNMAC": "057bde73-c9cf-46c1-8238-0c11944dce55",
    "hostedCheckoutId": "b40ffd58-18ad-4fd6-bc2b-1fdab76bf884",
    "merchantReference": "xxxxT2000001069",
    "partialRedirectUrl": "pay1.preprod.secured-by-ingenico.com/checkout/xxxx-d97bd29a12644a09a35dc73a09ca1571:b40ffd58-18ad-4fd6-bc2b-1fdab76bf884:cbb614fee3564a4a82c19d4bde64288d"
}
 [] []`

- If you go to this URL directly (copy/paste it from the log), does it then also trigger a 404? : Yes
- Is this behavior reproducible using the default Magento checkout : We didn't tried on default Magento

**Comment by Ingenico-Shoppingcarts-zz** [comment] 2020-02-24 13:54
To prevent miscommunication. There has also been direct email contact with your company on the status of the raised tickets. I received the response that all issues where handled via own code changes. I assume now that this was only related to the Locale issues for China. 
The language pack issue will be tackled in the upcoming release. 

The issue you have discussed in this post is related to the use of a second 3rd party module for creating a one step checkout. 
We are unable to reproduce the issue tried by our technical partner and me. All attempts create a new session when using the default Magento Checkout. 

For us to support issues related to multiple modules the reporter should contact all parties on the topic. Please reach out to the provider of the module to see if caching or similar functions impact the behavior and it might be fixed based on setting of the module. 

When they respond with feedback and the intention to help resolving you can connect us to find a solution. 

--- 
**The 404 page is rendered when a session is expired. This can be time related (2h) or cancellation by consumer.** 
---

**Comment by Jitheesh** [comment] 2020-02-26 09:10
This is happening for all orders, see today I tried to place an order and end with 404 again, I don't think it is related to third-party modules, because Ingenico is responding 404 urls in its response.

See full details here https://docs.google.com/document/d/1ihSmD6jP7LHSKIVkuKJhTwevq9ySKB6ijHWmk8wElZQ/edit

**Comment by kanduvisla** [comment] 2020-06-02 07:47
I'm closing this issue since there has been no activity for the last 3 months.

**Closed as completed by kanduvisla** 2020-06-02 07:47 UTC
