### ISSUE TITLE
Online refund not avialble

### ISSUE THREAD

**Issue by Jitheesh** [Ingenico-ePayments/connect-extension-magento2#9] opened 2020-02-25 11:40 UTC
Ingenico\Connect\Gateway\CanRefund::handle() is returns false for most of the cases and because of this online refund option is not enabled for Ingenico payments.

We can see following  related issues
1. Order status is not refreshed properly, Cron job enabled and working correctly but to refresh order status we have to manually click 'refresh order status' button

2. When we clicking on 'refresh order' button, it fetch payment status and updated transaction messages correctly, example Transaction ID: "000000898710000120890000100001"
but transaction details not updated - it still showing Refundable status as No and status code as 800.
based on order history messages it should be 1000.
So this will confirm transaction details is not updated after clicking on 'refresh status' button.

3. For some orders refresh status response  is always 'CAPTURE_REQUESTED'
We can see that statusCode is getting new value, ie 900. but it have same payments status message. So that it won't update anything.
Example request :  /v1/8987/payments/000000898710000126640000100001

why above request is always respond  'CAPTURE_REQUESTED' status.

Additional notes:
- We are using latest version
- We don't have any admin customization 
- magento 2.3.3
- Cron jobs working fine
- Offline refund working fine

**Comment by rikvanthof** [comment] 2020-02-25 12:52
Ad 1) I looked in our systems and have found the transaction in our pre-production environment. I noticed that on that account you have not enabled webhooks. I can see an endpoint on your side that you have configured, but it is marked as inactive. This is the cause why your system isn't updated automatically as our system isn't sending your system any messages (and it never has in the past).

Ad 2) The status of the 000000898710000120890000100001 transaction in our system is indeed PAID and we see your request to retrieve the status coming in. I will get the team to investigate this one.

Ad 3) Multiple numeric statusCodes are mapped to the status CAPTURE_REQUESTED, statusCode 900 is mapped to CAPTURE_REQUESTED, so you are seeing the correct status. The transaction hasn't been captured yet and as soon as it has been the status will change to PAID.

**Comment by Jitheesh** [comment] 2020-02-26 06:55
Hi @rikvanthof 

We have enabled webhooks, but still facing same issues.

1) Order status is not refreshed, it is always showing 800 status, no other data is coming from API
We have tried clicking 'refresh order status' button - still no luck
Additional q: 
1.a) How did this normally work, when will actual payment capture completed? 
1.b) We can see invoice created with paid status in Magento, but actual Ingenico payment transaction status is 800, why it is handling like this?

2) We have another example, please check 000000898710000131330000100001

Complete transaction details and logs attached here : https://docs.google.com/document/d/1rdbji1gLaRCI0mDJhEtvshd972ZLJsMbCFY4J7KBW98/edit 
( note - please request permission to view )

**Comment by Ingenico-Shoppingcarts-zz** [comment] 2020-02-26 07:29
Hi, unfortunate I was out of office yesterday. To prevent any confusion. 
We will follow-up on the issues raised. Improving the refund is already on the roadmap since it was flagged by me as being incomplete. 

The module is acting on the communication we receive from the api and webhooks. 
The intended design for the order flow would be:
Capture _requested (800) is sufficient to start fullfilment of the order. 
Change to substatus (900) is not communicated via a webhooks due to the architecture of the API and will be retrieved via the api call getpayment when an order is opend in Magento. 
The status pais (1000) is processed when we receive the webhook. 

Payment options that need additional data (bank transfer) are excluded for online refund in Magento and should be processed using our backend.  
Payment options that are online refundable will give a warning when trying to refund offline on order leverl or invoice level. 

Regarding your case. I will look in to the details if it is part of the currently raised tickets.

**Comment by Jitheesh** [comment] 2020-02-26 08:31
Hi @Ingenico-Shoppingcarts 

Thank you for your response.

Based on your last response, it looks like we have to open order from Magento to get status updates!

In our case, our system is designed via API calls, Most of the cases order is not opened from Magento admin. Refunds are created by using Magento API calls.  In this case how it will work?

**Comment by Ingenico-Shoppingcarts-zz** [comment] 2020-02-26 10:19
In this setup the use of the API is not taken in to account in this version. 
It is a valid point to cover this  on short notice.  

The issue that needs to be tackled is not supported in our webhooks.
As long as the main status is not updated, the case between capture_requested and paid. Moving the sub-status isRefundable from false to true does not trigger a webhook. 

There are two actions in my opinion to use:
1. User initiated action => opening the order
2. periodical check -> Cronjob for getPayment 

The periodical check can still conflict with the API based refunds of Magento since it might not have the latest status in between cronjobs.

I will discuss with our partner if there is an option to react on the API refund. 
If you have any suggestions feel free to share. 

Keep in mind that the architecture of our system is setup in a way that the confirmation of a guaranteed payment, meaning you are able to fulfill the order is not the same as the order is refundable. 

We do not queue refunds, meaning we need confirmation from the payment options that the funds is available for refunding. This is the moment we change the status isRefundable=true.

**Comment by Jitheesh** [comment] 2020-02-26 10:25
@Ingenico-Shoppingcarts why can't you send an payment status API request before processing CanRefund() ?

Currently it is checking from already saved payment transaction data

**Comment by Ingenico-Shoppingcarts-zz** [comment] 2020-02-26 10:32
The current status was already under review and based on your feedback from yesterday changed in priority. 

We are looking in how to improve the current flow to get the correct status without using a in order button. 
If canrefund() function from Magento 2 covers the scenario for both in admin and API usage it might be the way to go for sending the getPayment call to ingenico.

**Comment by Jitheesh** [comment] 2020-02-27 05:20
Hi @Ingenico-Shoppingcarts 
Issue 2)
Based on my investigation I found this line of code is creating issues with transaction update 
https://github.com/Ingenico-ePayments/connect-extension-magento2/blob/e0c2e89951220596712c499774cb5bb55d00ad82/Model/Ingenico/Action/RetrievePayment.php#L108

ie, old transaction is added again to order related object and it overrides new updates 
Here it is adding new transaction updates but later it is overrides by previous old transaction object 
https://github.com/Ingenico-ePayments/connect-extension-magento2/blob/e0c2e89951220596712c499774cb5bb55d00ad82/Model/StatusResponseManager.php#L103

I've removed this line of code to resolve this issue https://github.com/Ingenico-ePayments/connect-extension-magento2/blob/e0c2e89951220596712c499774cb5bb55d00ad82/Model/Ingenico/Action/RetrievePayment.php#L108

Issue 3)
Can we resolve this by updating following line of code https://github.com/Ingenico-ePayments/connect-extension-magento2/blob/e0c2e89951220596712c499774cb5bb55d00ad82/Model/Ingenico/Action/RetrievePayment.php#L102
with
`  if ($updateStatus->statusOutput->statusCode !== $currentStatus->statusOutput->statusCode) `

So it will get 900 updates.
Can we refund an order with 900 status?

**Comment by Ingenico-Shoppingcarts-zz** [comment] 2020-02-27 08:00
Thanks for making the effort. 
When the refund status is shown is payment option dependent.
For card payments the 900 does contain the status to refund. 
I will have to ask our partner to verify your feedback. 
They are also reviewing the refund flow and will be able to update on this topic on short notice. 
The biggest challenge in the API communication is that this status change is not represented by a webhook in case of switching beteen 800 and 900.

**Comment by kanduvisla** [comment] 2020-02-27 09:11
Hi @Jitheesh ,

Thanks for your effort into fixing this issue. The fix you provided for issue 2 is the same issue we found, so your fix is in line with ours. I am currently extending our integration test suite to make sure that this won't break anything else. Especially the `ApproveRefund`, `CancelRefund` and `UndeCapturePaymentObserver`-classes that make use of the `RetrievePayment::process()`-method.

When the integration tests are done and they're all green I will look at issue 3. I'll check if we can use the fix you provided here. I am a bit worried about using the statusCode, since the API documentation states:

> You should not write new business logic based on this property as it will be deprecated in a future version of the API.

So this could introduce a forward-compatibility issue.

**Comment by kanduvisla** [comment] 2020-04-02 09:45
Hi @Jitheesh ,

The issue with online refund not being available has been fixed in version `2.2.0` of the module that has been released today.

**Closed as completed by kanduvisla** 2020-04-02 09:45 UTC
Labels: internal
